In [48]:
import numpy as np
import tensorflow as tf

In [2]:
a = 2
b = 3

In [3]:
c = tf.add(a, b, name='Add')

In [4]:
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [5]:
sess = tf.Session()
print(sess.run(c))
sess.close()

5


In [8]:
with tf.Session() as sess:
    print(sess.run(c))

5


In [9]:
x = 2
y = 3

In [10]:
add_op = tf.add(x, y, name='Add')
mul_op = tf.multiply(x, y, name='Multiply')
pow_op = tf.pow(add_op, mul_op, name='Power')
useless_op = tf.multiply(x, add_op, name='Useless')

In [11]:
with tf.Session() as sess:
    pow_out, useless_out = sess.run([pow_op, useless_op])
    print(pow_out, useless_out)

15625 10


In [12]:
a = tf.constant(2)
b = tf.constant(3)
c = a + b

In [13]:
with tf.Session() as sess:
    print(sess.run(c))

5


In [14]:
a = tf.constant(2, name='A')
b = tf.constant(3, name='B')
c = tf.add(a, b, name='Sum')

In [15]:
with tf.Session() as sess:
    print(sess.run(c))

5


In [16]:
s = tf.constant(2.3, name='scalar', dtype=tf.float32)
m = tf.constant([[1, 2], [3, 4]], name='matrix')

In [17]:
with tf.Session() as sess:
    print(sess.run(s))
    print(sess.run(m))

2.3
[[1 2]
 [3 4]]


In [18]:
s = tf.Variable(2, name='scalar')
m = tf.Variable([[1, 2], [3, 4]], name='matrix')
W = tf.Variable(tf.zeros([784, 10]))

In [19]:
W.shape

TensorShape([Dimension(784), Dimension(10)])

In [26]:
#del s, m, W
tf.reset_default_graph()

In [27]:
s = tf.get_variable('scalar', initializer=tf.constant(2))
m = tf.get_variable('matrix', initializer=tf.constant([[1, 2], [3, 4]]))
W = tf.get_variable('weight_matrix', shape=(784, 10), initializer=tf.zeros_initializer())

In [28]:
a = tf.get_variable(name='var1', initializer=tf.constant(2))
b = tf.get_variable(name='var2', initializer=tf.constant(3))
c = tf.add(a, b, name='Add1')

In [30]:
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

FailedPreconditionError: Attempting to use uninitialized value var1
	 [[Node: _retval_var1_0_0 = _Retval[T=DT_INT32, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](var1)]]

In [31]:
a = tf.get_variable(name='A', initializer=tf.constant(2))
b = tf.get_variable(name='B', initializer=tf.constant(3))
c = tf.add(a, b, name='Add')
init_op = tf.global_variables_initializer()

In [32]:
with tf.Session() as sess:
    print(sess.run(init_op))
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

None
2
3
5


In [33]:
weights = tf.get_variable(name='W', shape=[2, 3], initializer=tf.truncated_normal_initializer(stddev=0.01))
biases = tf.get_variable(name='b', shape=[3], initializer=tf.zeros_initializer())
init_op = tf.global_variables_initializer()

In [35]:
with tf.Session() as sess:
    sess.run(init_op)
    W, b = sess.run([weights, biases])
    print("weights = {}".format(W))
    print("biases = {}".format(b))

weights = [[ 0.00084767 -0.00977745 -0.00682827]
 [-0.00822718 -0.00728612  0.00954679]]
biases = [0. 0. 0.]


In [38]:
a = tf.placeholder(tf.float32, shape=[5])
b = tf.placeholder(dtype=tf.float32, shape=None, name=None)
X = tf.placeholder(tf.float32, shape=[None, 784], name='input')
Y = tf.placeholder(tf.float32, shape=[None, 10], name='label')

In [39]:
a = tf.constant([5, 5, 5], tf.float32, name='A')
b = tf.placeholder(tf.float32, shape=[3], name='B')
c = tf.add(a, b, name='Add')

In [40]:
with tf.Session() as sess:
    print(sess.run(c))

InvalidArgumentError: You must feed a value for placeholder tensor 'B_2' with dtype float and shape [3]
	 [[Node: B_2 = Placeholder[dtype=DT_FLOAT, shape=[3], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[Node: Add_1/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7_Add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'B_2', defined at:
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 497, in start
    self.io_loop.start()
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/asyncio/base_events.py", line 1434, in _run_once
    handle._run()
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2901, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-39-504b71e8c18d>", line 2, in <module>
    b = tf.placeholder(tf.float32, shape=[3], name='B')
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1735, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4925, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'B_2' with dtype float and shape [3]
	 [[Node: B_2 = Placeholder[dtype=DT_FLOAT, shape=[3], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[Node: Add_1/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7_Add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [42]:
with tf.Session() as sess:
    d = {b: [1, 2, 3]}
    print(sess.run(c, feed_dict=d))

[6. 7. 8.]


In [43]:
X = tf.placeholder(tf.float32, shape=[None, 784], name='X')

In [44]:
weight_initier = tf.truncated_normal_initializer(mean=0, stddev=0.01)
W = tf.get_variable(name='Weight', dtype=tf.float32, shape=[784, 200], initializer=weight_initier)
bias_initier = tf.constant(0., shape=[200], dtype=tf.float32)
b = tf.get_variable(name='Bias', dtype=tf.float32, initializer=bias_initier)

In [45]:
x_w = tf.matmul(X, W, name='MatMul')
x_w_b = tf.add(x_w, b, name='Add')
h = tf.nn.relu(x_w_b, name='ReLU')

In [46]:
init_op = tf.global_variables_initializer()

In [49]:
with tf.Session() as sess:
    sess.run(init_op)
    d = {X: np.random.rand(100, 784)}
    print(sess.run(h, feed_dict=d))

[[0.11465734 0.22986935 0.         ... 0.         0.         0.2977137 ]
 [0.09458455 0.18094213 0.         ... 0.         0.02460318 0.2783262 ]
 [0.177083   0.25938612 0.         ... 0.0059197  0.         0.30098492]
 ...
 [0.07372604 0.05998296 0.         ... 0.0140877  0.0810242  0.17726102]
 [0.09269682 0.12367599 0.         ... 0.         0.         0.23221606]
 [0.12058407 0.14429347 0.         ... 0.14267872 0.07573949 0.18088087]]


In [57]:
tf.reset_default_graph()
a = tf.constant(2)
b = tf.constant(3)
c = tf.add(a, b)

In [58]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./tf_logdir', sess.graph)
    print(sess.run(c))
    

5


In [59]:
tf.reset_default_graph()
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
c = tf.add(a, b, name='addition')

In [60]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./tf_logdir', sess.graph)
    print(sess.run(c))

5


In [61]:
tf.reset_default_graph()
x_scalar = tf.get_variable('x_scalar', shape=[], initializer=tf.truncated_normal_initializer(mean=1, stddev=1))

In [62]:
first_summary = tf.summary.scalar(name='My_first_scalar_summary', tensor=x_scalar)

In [63]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./tf_logdir/', sess.graph)
    for step in range(100):
        sess.run(init)
        summary = sess.run(first_summary)
        writer.add_summary(summary, step)
    print("Done with writting scalar summary")
    

Done with writting scalar summary


In [66]:
tf.reset_default_graph()
x_scalar = tf.get_variable('x_scalar', shape=[], initializer=tf.truncated_normal_initializer(mean=1, stddev=1))
x_matrix = tf.get_variable('x_matrix', shape=[30, 40], initializer=tf.truncated_normal_initializer(mean=1, stddev=1))

In [67]:
scalar_summary = tf.summary.scalar('My_scalar_summary', x_scalar)
histogram_summary = tf.summary.histogram('My_histogram_summary', x_matrix)

In [68]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./tf_logdir', sess.graph)
    for step in range(100):
        sess.run(init)
        summary1, summary2 = sess.run([scalar_summary, histogram_summary])
        writer.add_summary(summary1, step)
        writer.add_summary(summary2, step)
    print("Done writing the summaries")

Done writing the summaries


In [69]:
tf.reset_default_graph()
x_scalar = tf.get_variable('x_scalar', shape=[], initializer=tf.truncated_normal_initializer(mean=1, stddev=1))
x_matrix = tf.get_variable('x_matrix', shape=[30, 40], initializer=tf.truncated_normal_initializer(mean=1, stddev=1))

In [70]:
scalar_summary = tf.summary.scalar('My_scalar_summary', x_scalar)
histogram_summary = tf.summary.histogram('My_histogram_summary', x_matrix)

In [71]:
merged = tf.summary.merge_all()

In [73]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./tf_logdir', sess.graph)
    for step in range(100):
        sess.run(init)
        summary = sess.run(merged)
        writer.add_summary(summary, step)
    print("Done writting the summaries")

Done writting the summaries


In [74]:
tf.reset_default_graph()

In [75]:
w_gs = tf.get_variable('W_Grayscale', shape=[30, 10], initializer=tf.truncated_normal_initializer(mean=0, stddev=1))
w_c = tf.get_variable('W_Color', shape=[50, 30], initializer=tf.truncated_normal_initializer(mean=0, stddev=1))

In [76]:
w_gs_reshaped = tf.reshape(w_gs, (3, 10, 10, 1))
w_c_reshaped = tf.reshape(w_c,(5, 10, 10, 3))

In [77]:
gs_summary = tf.summary.image('Grayscale', w_gs_reshaped)
c_summary = tf.summary.image('Color', w_c_reshaped, max_outputs=5)

In [78]:
merged = tf.summary.merge_all()

In [81]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./tf_logdir', sess.graph)
    sess.run(init)
    summary = sess.run(merged)
    writer.add_summary(summary)
    print("Done writing the summaries")

Done writing the summaries
